name: build and deploy

on: [push, pull_request]

env:
  IMAGE_NAME: android-ndk

jobs:
  build-and-deploy:
    strategy:
      matrix:
        ndk-version: [r22b]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build android-ndk:${{ matrix.ndk-version }}
      run: |
        docker build . -t ${IMAGE_NAME}:${{ matrix.ndk-version }} --build-arg NDK_VERSION=${{ matrix.ndk-version }}
    - name: docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: push android-ndk:${{ matrix.ndk-version }}
      run: |
        docker tag ${IMAGE_NAME}:${{ matrix.ndk-version }} ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:${{ matrix.ndk-version }}
        docker push ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:${{ matrix.ndk-version }}